### ISSUE TITLE
download problem

### ISSUE THREAD

**Issue by welbeckzhou** [michaildoukas/head2head#1]
Something wrong happens when downloading files for face reconstruction and flownet in scripts/download_files.py, the file in first url : https://www.dropbox.com/s/woijiy3gqgfz1j7/files.zip?dl=1, cannot be found. What's this file used for? And how to download it?

**Comment by michaildoukas** [comment]
Please try to pull the latest version of the code. There was a change in files for 3D face reconstruction (see README). For the time being you need to obtain LSFM model files from [here](https://xip.uclb.com/i/healthcare_tools/LSFM.html
) and place the acquired files under ```preprocessing/files```. However, the rest essential files can be still downloaded using ```scripts/download_files.py```.

**Comment by welbeckzhou** [comment]
Thank you so much!
