### ISSUE TITLE
pytorch version error

### ISSUE THREAD

**Issue by visonpon** [michaildoukas/head2head#10]
@michaildoukas, thanks for your great work, and when I try to use it, I got some PyTorch version compatible errors.

since the flownet_pytorch relies on pytorch0.4.1 and torchvision0.2.2, but this work relies on pytorch1.4 and torchvison0.5.
when the flownet_pytorch compile success,  the facenet_pytorch raise an error `no module named torchvison.ops` because the torchvison-0.2.2 is low, but when I change the PyTorch to 1.4 and torchvision to 0.5, I got an error `Undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs` that in the flownet_pytorch project it seems to have to use [torch0.4.1...](https://github.com/NVIDIA/flownet2-pytorch/issues/122)

so these two frameworks conflicting with each other, hope you can help, thanks~

**Comment by cyrala** [comment]
> @michaildoukas, thanks for your great work, and when I try to use it, I got some PyTorch version compatible errors.
> 
> since the flownet_pytorch relies on pytorch0.4.1 and torchvision0.2.2, but this work relies on pytorch1.4 and torchvison0.5. when the flownet_pytorch compile success, the facenet_pytorch raise an error `no module named torchvison.ops` because the torchvison-0.2.2 is low, but when I change the PyTorch to 1.4 and torchvision to 0.5, I got an error `Undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs` that in the flownet_pytorch project it seems to have to use [torch0.4.1...](https://github.com/NVIDIA/flownet2-pytorch/issues/122)
> 
> so these two frameworks conflicting with each other, hope you can help, thanks~

Hi, I also encounterd this problem, have you solved it?
