### ISSUE TITLE
Create dataset without LSFM

### ISSUE THREAD

**Issue by thanisornsr** [michaildoukas/head2head#3]
Hello, 

I have a question about creating my own dataset. In order to create my own dataset, are there any alternatives to LSFM model since I can't request for the LSFM. I am only master student which is not pass their qualification. Would you mind giving me some recommendation?

All the best,
Thanisorn

**Comment by michaildoukas** [comment]
Unfortunately this Head2Head implementation currently supports only the LSFM model. In principle other 3D Morphable Models can be used to construct the NMFC conditional input images, but I would suggest requesting access to LSFM files.

Kindly,
Michail

**Comment by thanisornsr** [comment]
Thank you for your kindly reply. I will ask my faculty for the requesting. Anyway, I will try to use other 3D Morphable Models as well just in case I cannot get the LSFM.

Big thanks,
Thanisorn

**Comment by ketan4373** [comment]
Hello @thanisornsr, Kindly provide way to use 3D Morphable Models if you have got success. Also if you can provide quality of results if you have got any. Thanks.
